workflows

diff --git a/.github/workflows/testcoverage.yml b/.github/workflows/testcoverage.yml
--- a/.github/workflows/testcoverage.yml
+++ b/.github/workflows/testcoverage.yml
@@ -42,13 +42,11 @@ jobs:
 
       - name: Check coverage percentage
         run: |
-          COVERAGE_THRESHOLD=70
-          sleep 60
-          ACTUAL_COVERAGE=$(curl -s "https://codecov.io/api/gh/${{ github.repository }}/commits/${{ github.sha }}" | jq -r '.commit.totals.c')
-          echo $ACTUAL_COVERAGE
-          if (( $(echo "$ACTUAL_COVERAGE >= $COVERAGE_THRESHOLD" | bc -l) )); then
-            echo "Code coverage is within the threshold."
+          COVERAGE_PERCENTAGE=$(cat ./coverage/lcov-report/index.html | grep -o -P '(?<=data-cov="line">)[0-9]+(?=%</span>)')
+
+          if [ "$COVERAGE_PERCENTAGE" -ge 80 ]; then
+            echo "Coverage is greater than or equal to 80%."
           else
-            echo "Code coverage is below the threshold. Expected: $COVERAGE_THRESHOLD%, Actual: $ACTUAL_COVERAGE%"
-          exit 1
+            echo "Coverage is less than 80%."
+            exit 1  # Fail the workflow if coverage is less than 80%
           fi
